---
micronaut:
    application:
        name: user_profile_svc
    server:
        port: 8080

---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
#    ssl:
#        enabled: true
#    apply-connection-string:
 #       userName: test-db1
 #       password:      database: testdb
